version: 0.2

phases:
  pre_build:
    commands:
      - echo prebuildphase

  build:
    commands:
      - cd lambda
      - ls -R
      - echo Installing source NPM dependencies...
      - npm install
      - echo Zipping the Lambda function code...
      - zip -r lambda_function_payload.zip .

  post_build:
    commands:
      - echo Build completed
      - echo Deploying Lambda function...
      - aws lambda update-function-code --function-name eagler-lambda-verify-mail --zip-file fileb://lambda_function_payload.zip
